apiVersion: v1
kind: ConfigMap
metadata:
  name: kubecost
data:
  prometheus-alertmanager-endpoint: http://alertmanager-main.openshift-monitoring.svc.cluster.local
  prometheus-server-endpoint: http://prometheus-k8s.openshift-monitoring.svc.cluster.local
  kubecost-token: not-applied
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: kubecost
data:
  nginx.conf: |
    gzip_static  on;

    upstream api {
        server kubecost.kubecost:9001;
    }

    upstream model {
        server kubecost.kubecost:9003;
    }

    server {
        listen 9090;
        server_name _;
        root /var/www;
        index index.html;
        add_header Cache-Control "no-cache";
        add_header ETag "1.30.0";
        location /api/ {
            proxy_pass http://api/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /model/ {
            proxy_pass http://model/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
