apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubecost
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubecost
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: 'ajaytripathy/kubecost-frontend:prod-1.30.0'
          name: cost-analyzer-frontend
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 55Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: nginx-conf
            - mountPath: /etc/ssl/certs
              name: all-certs
        - env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: prometheus-server-endpoint
                  name: kubecost
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/configs/key.json
            - name: KUBECOST_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: kubecost-token
                  name: kubecost
            - name: GRAFANA_URL
              valueFrom:
                configMapKeyRef:
                  key: grafanaURL
                  name: external-grafana-config-map
          image: 'ajaytripathy/kubecost:prod-1.30.0'
          name: cost-analyzer-server
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 55Mi
          volumeMounts:
            - mountPath: /var/configs
              name: persistent-configs
            - mountPath: /etc/ssl/certs
              name: all-certs
        - env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: prometheus-server-endpoint
                  name: kubecost
            - name: CLOUD_PROVIDER_API_KEY
              value: AIzaSyDXQPG_MHUEy9neR7stolq6l0ujXmjJlvk
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/configs/key.json
            - name: CONFIG_PATH
              value: /var/configs/
            - name: KUBECOST_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: kubecost-token
                  name: kubecost
          image: 'ajaytripathy/kubecost-cost-model:prod-1.30.0'
          imagePullPolicy: Always
          name: cost-model
          readinessProbe:
            failureThreshold: 200
            httpGet:
              path: /healthz
              port: 9003
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: 800m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 55Mi
          volumeMounts:
            - mountPath: /var/configs
              name: persistent-configs
            - mountPath: /etc/ssl/certs
              name: all-certs
      initContainers:
        - env:
          image: 'ajaytripathy/kubecost-init:prod-1.30.0'
          name: cost-analyzer-init-certs
          command:
          - "update-ca-certificates"
          volumeMounts:
            - mountPath: /usr/local/share/ca-certificates
              name: prom-ca
            - mountPath: /etc/ssl/certs
              name: all-certs
          securityContext:
            runAsUser: 0
        - env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: prometheus-server-endpoint
                  name: kubecost
          image: 'ajaytripathy/kubecost-init:prod-1.30.0'
          name: cost-analyzer-init
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: all-certs
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: kubecost
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: default.conf
            name: nginx-conf
          name: nginx-conf
        - name: persistent-configs
          persistentVolumeClaim:
            claimName: kubecost
        - name: prom-ca
          configMap:
            name: prom-ca
        - name: all-certs
          emptyDir: {}
