apiVersion: v1
kind: Service
metadata:
  name: kubecost
spec:
  ports:
    - name: server
      port: 9001
      targetPort: 9001
    - name: model
      port: 9003
      targetPort: 9003
    - name: frontend
      port: 9090
      targetPort: 9090
  selector:
    app: kubecost
  type: ClusterIP
