apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubecost
spec:
  endpoints:
    - port: model
      honorLabels: true
      interval: 1m
      scrapeTimeout: 10s
      path: /metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - kubecost
  selector:
    matchLabels:
      app: kubecost
